baseURL = "https://gohugo.io"
title = "ヰ世界製菓"
subtitle = "せかせかせかせかせかせかっかっかん"
author = "Cortmiem"
paginate = 10
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "sk1"
timeout = "3600s"

[Params]
mainSections = "post"
subtitle = "せかせかせかせかせかせかっかっかん"

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[taxonomies]
category = "categories"

[markup.goldmark.renderer]
unsafe= true